default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_filepath: "./private_keys/AuthKey_#{ENV['ASC_KEY_ID']}.p8",
      duration: 1200,
      in_house: false
    )

    build_app(
      project: "VoiceRecorder.xcodeproj",
      scheme: "VoiceRecorder",
      configuration: "Release",
      export_method: "app-store",
      destination: "generic/platform=iOS",
      xcargs: "CODE_SIGN_STYLE=Manual PROVISIONING_PROFILE_SPECIFIER='VoiceRecorder AppStore'",
      export_options: {
        provisioningProfiles: {
          "com.hakisung.VoiceRecorder" => "VoiceRecorder AppStore"
        }
      },
      clean: true,
      output_directory: "./build"
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true,
      skip_submission: true
    )
  end
end
